version: 0.0
os: linux

files:
  - source: /home/ubuntu/myfiles/
    destination: /home/ubuntu/myfiles/
    overwrite: true

permissions:
  - object: /home/ubuntu/myfiles
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - timeout: 300
      runas: ubuntu
      location: deploy.sh

  AfterInstall:
    - timeout: 600
      runas: ubuntu
      location: deploy.sh

  ApplicationStart:
    - timeout: 1200
      runas: ubuntu
      location: deploy.sh
