version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myfiles/  # Adjust this destination path to match your application

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - timeout: 300
      runas: ubuntu
      location: deploy.sh

  AfterInstall:
    - timeout: 600
      runas: ubuntu
      location: deploy.sh

  ApplicationStart:
    - timeout: 1200
      runas: ubuntu
      location: deploy.sh
