version: 0.0
os: linux
files:
  - source: index.html
    destination: /home/ssm-user/code/
permissions:
  - object: /home/ssm-user
    owner: ssm-user
    group: ssm-user
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 1200
      runas: ubuntu
