version: 0.0
os: linux
files:
  - source: /*
    destination: /home/ubuntu/task/
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: deploy.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: deploy.sh
      timeout: 1200
      runas: ubuntu
