version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/myapp/  # Adjust this destination path to match your application

permissions:
  - object: /var/www/myapp/
    owner: ubuntu
    group: ubuntu
