version: 0.0

os: ubuntu

files:
  - source: /tmp/devops-repo/
    destination: /var/www/html/
    overwrite: true

hooks:
  BeforeInstall:
    - location: /tmp/devops-repo/before_install.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: /tmp/devops-repo/after_install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: /tmp/devops-repo/start_server.sh
      timeout: 60
      runas: root

  ApplicationStop:
    - location: /tmp/devops-repo/stop_server.sh
      timeout: 60
      runas: root
