version: 0.0

os: ubuntu

files:
  - source: /test-1devops/
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: after_install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: start_server.sh
      timeout: 60
      runas: root

  ApplicationStop:
    - location: stop_server.sh
      timeout: 60
      runas: root
