version: 0.0
os: linux
files:
  - source: s3://test-1devops/
    destination: /home/ubuntu/task/
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ubuntu
