version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # or choose an appropriate Node.js version
      
artifacts:
  files:
    - '**/*'

post_build:
  commands:
    # Assuming you've configured your AWS CLI with credentials
    - aws s3 sync dist/devops/ s3://task-1dev2000 --exclude "dist/devops/*"

