version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18  # Use the Node.js version you need
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - git clone https://github.com/Seenu-2000/devops.git /tmp/devops-repo
  build:
    commands:
      - cd /tmp/devops-repo
      - zip -r deployment.zip .  # Create a ZIP archive of all files in the directory
  post_build:
    commands:
      - aws s3 cp /tmp/devops-repo/deployment.zip s3://test-1devops/deployment.zip  # Upload the ZIP archive to S3
      - echo Build completed on `date`
artifacts:
  files:
    - 'appspec.yml'
    - 'before_install.sh'
    - 'after_install.sh'
    - 'start_server.sh'
    - 'stop_server.sh'
    - 'nodescript.js'
    - 'package.json'
