version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build started on `date`
      # You can add commands to build your project here if needed.

artifacts:
  files:
    - index.html
    - styles.css
    # Add any other necessary files here

cache:
  paths:
    - '/root/.npm' # Add any other paths to cache as needed
