version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18  # Use the Node.js version you need
    commands:
      - echo Nothing to do in the install phase...
 pre_build:
    commands:
      - git clone https://github.com/Seenu-2000/devops.git /tmp/devops-repo

  build:
    commands:
      - aws s3 sync /tmp/devops-repo/ s3://test-1devops --exclude ".git/*" --exclude "task/*"
      - cd /tmp/devops-repo  # Change to the repository directory
      
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
    - 'index.html'
    - 'appspec.yml'
    - 'before_install.sh'
    - 'after_install.sh'
    - 'start_server.sh'
    - 'stop_server.sh'
