version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Use a more recent Node.js version (adjust as needed)
    commands:
      - echo "Installing dependencies..."
      - npm config set package-lock false  # Disable package-lock.json to avoid issues
      - npm install -g @angular/cli@10.0.8

  build:
    commands:
      - echo "Building Angular project..."

post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/devops/ s3://task-1dev2000 --delete
